### ISSUE TITLE
After the service  nfs-server-provisioner  is restarted, the following error will be reported: access denied by server while mounting

### ISSUE THREAD

**Issue by pyy000pine** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#111]

**Comment by Wieneo** [comment]
This happens in our setup too!

**Comment by Wieneo** [comment]
You can fix the error by adding the following to the securityContext of the container:
privileged: true

I will have a look at how we can patch this properly.

**Comment by EsDmitrii** [comment]
the same 
<img width="708" alt="Screenshot 2023-08-23 at 15 14 47" src="https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/assets/124890665/0dab246c-c2e6-4c1b-9acc-90d0cbd64322">

**Comment by EsDmitrii** [comment]
> You can fix the error by adding the following to the securityContext of the container:
privileged: true


this doesn't work, error still exists 

<img width="576" alt="Screenshot 2023-08-23 at 15 30 18" src="https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/assets/124890665/21ce8c17-d1b0-4640-9f10-baf6bc27de35">

**Comment by kaiquerass** [comment]
~~same problem here and the privileged config does not work either.~~

I found out the deployment for the nfs server was not using persistence, that way, obviously, every restart would result in empty directory under `/etc/exports/`.
Persistence configured and the problem is solved.

Sorry for the mistake, but I'll let this comment here because someone could be missing persistence configuration too.

**Comment by bytemarcz** [comment]
Hitting some of the same issues. Not sure what I'm missing for the ganesha specific nfs provisioner. It seems we are running it across multiple environments. Two of our environments are fine but the third environment seems to not be mounting. 

On the nfs side I did attempt to add the mountOptions detailed here: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/34

After deleting the existing pvcs I'm thinking the change worked but having difficulty validating this part. 

I mainly want to confirm for the ganesha provisioner if I need the nfs-common and nfs-kernel-server packages installed. It seems we have nfs-common getting installed but can't find anywhere in the docs if these are required. If someone can confirm if those packages are required. 

Main issue is that pods are going down and not mounting to the existing pvcs.

**Comment by apham0001** [comment]
By default, persistence is set to `false` in the Helm chart:

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/charts/nfs-server-provisioner/values.yaml#L41

Would it be possible to set it to `true` by default instead?
