### ISSUE TITLE
Changing mountOptions

### ISSUE THREAD

**Issue by alexandrebunn** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#119]
Is there a way to change the mountOptions of an existing pv and its pvc of a nfs-server deployed?

I've changed custom-values.yaml adding proto parameter and changing rsize and wsize but it didn't apply at pv definition.

See below the change at custom-values.yaml

```yaml
  mountOptions:
    - vers=3
    - retrans=2
    - timeo=30
    - nosuid
    - rsize=8388608
    - wsize=8388608
    - proto=tcp
```

After apply with "helm upgrade -i" 

The pv created didn't change these parameters (the proto=tcp parameter didn't take effect):

```yaml
apiVersion: v1
kind: PersistentVolume
...
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-volume-ssd
    namespace: myns
    resourceVersion: "108524084"
    uid: 792cc3eb-825a-4948-b99d-bfa54b504481
  mountOptions:
  - vers=3
  - retrans=2
  - timeo=30
  - nosuid
  - rsize=8388608
  - wsize=8388608
```

**Comment by inzanez** [comment]
As far as I can see, the `mountOptions` should be applied to the `storageClass`. I would assume that this resulted in new volumes being created with the changed mount options.
For already existing PVs, you would have to edit the PV directly and then have the Kubernetes nodes re-mount that volume. I did that by restart the worker nodes one by one. I know, that might not be the best way but it definitely worked.
