### ISSUE TITLE
k8s.gcr.io registiry will be frozen by 3rdApr-2023

### ISSUE THREAD

**Issue by mahendra03** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#121]
Hi Team,

We have seen k8s notification stating - k8s.gcr.io image registry will be frozen from the 3rd of April 2023 ,
so as of now repository is repository: k8s.gcr.io/sig-storage/nfs-provisioner and it will be like registry.k8s.io/sig-storage/nfs-provisioner correct ? 

k8s.gcr.io/sig-storage/nfs-provisioner - This registry will be there but no more changes to it?

What any other changes we need to take care , can you please confirm?

**Comment by kvaps** [comment]
Hi. A new images currently are not publishing at all, we have a big problem with that, see https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/115

**Comment by mahendra03** [comment]
Hi @kvaps , If we are using chart version 1.4.0 and registry version v3.0.1 by when we need to upgrade ? when this will be redundant 3-Apr-2023?

**Comment by kvaps** [comment]
Well, the old images will continue existing in this registry, so you can updated at any time when fix will be available

**Comment by mahendra03** [comment]
Thanks for your reply @kvaps
