### ISSUE TITLE
Issues when using more replicas! 

### ISSUE THREAD

**Issue by dev-ago** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#123]
Reopening this Issue:

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/40

**Comment by ahmedalmulki** [comment]
I have the same error in GKE; not working with more replicas!

**Comment by kvaps** [comment]
Nfs-server-provisioner is not supposed for working in multiple replicas.
Can you tell more about backing storage you're using? Does it support `ReadWriteMany` and if so, why do you need a `nfs-server-provisioner` for it?

**Comment by ahmedalmulki** [comment]
I am using gcePersistentDisk, which is not supporting ReadWriteMany; I thought this project would be taken off the replication between replicas.
If this project does not support multiple replicas, why is it mentioned in the helm in values.yaml .
