### ISSUE TITLE
Failed pull image (Helm chart)

### ISSUE THREAD

**Issue by sseverops** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#125]
Failed to pull image "registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8": failed to resolve reference "registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8": registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8: not found

**Comment by cwrau** [comment]
We're facing the same problem 👍️

**Comment by kvaps** [comment]
fixed by https://github.com/kubernetes/k8s.io/pull/4893
/close
