### ISSUE TITLE
nfs storage size modification impact

### ISSUE THREAD

**Issue by mahendra03** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#127]
Hi @kvaps ,

We are using GKE and our nfs with single zonal and our current storage is 100Gi , if we increase the storage to 300Gi will it destroy and create new storage 300Gi and there will be data loss?

or it will just change the storage to 300Gi with no loss of data?

**Comment by mahendra03** [comment]
Hi @kvaps - Can you help me on this since nfs world is new to me , I am used to of using PV and PVC so looking for your support on this please?

**Comment by Shawn1874** [comment]
Seems like more of a question that could be answered with GKE documentation.  Is the NFS storage you provisioned elastic?  EFS type storage in a cloud environment is supposed to be elastic.  If you make any progress or learn anything else on your own please post and let us know what you found.
