### ISSUE TITLE
How to specify namespace when installing nfs-server-provisioner as sub-chart

### ISSUE THREAD

**Issue by sasathy1** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#135]
I would like to install nfs-server-provisioner as a sub-chart in the same namespace as the parent. Is there a way to do that today? 

**Values.yaml contents:**
  persistence:
    # Enables persistence
    #  -> Crucial so that the provisioner recognizes itself after restarting
    enabled: true
    size: 1.5Gi
  storageClass:
    # Name of the storage class that will be managed by the provisioner
    name: nfs

The pod and the pvcs are always in the default namespace even though the parent chart is in a different namespace. Is there a way to specify the namespace or do a "namespaceOverride" like in longhorn which allows to do just that - https://github.com/longhorn/longhorn/issues/2031

**Comment by glawler** [comment]
You can specify this in the helm command:

```
helm install -n my-namespace --create-namespace stable/nfs-server-provisioner --values values.yaml
```

**Comment by sasathy1** [comment]
Sorry, to be clear, I was mentioning the scenario where nfs is a sub-chart of another chart. I am not able to provision in the right namespace when used as a sub-chart. 

For other similar systems, something like "namespaceOverride" exists which is precisely meant for installing in the right namespace when installing as a subchart. For instance, longhorn has something similar - 
https://github.com/longhorn/longhorn/issues/2031. 

May be something like that is needed for nfs too to allow this functionality?

**Comment by sasathy1** [comment]
@kvaps: could you or someone else among the owners help with this? would really appreciate the help. thanks in advance.
