### ISSUE TITLE
How to export and mount pvc for nfs-ganesha to different cluster pv and pvc

### ISSUE THREAD

**Issue by mahendra03** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#137]
Hi Team,

We are using nfs-ganesha-provisoner for my GKE deployment in one namespace and this create a pod and disk.
Due to GKE version upgrade we are provisioning new GKE cluster and that is using different namespace and how to export data from old GKE to new GKE.

How I can export exisiting NFS volume and mount it to PVC?

Thanks,
Mahendra

**Comment by EsDmitrii** [comment]
U can copy all data from NFS PV from /export to the new PV in new cluster
kubectl cp ns/pod:/path/to/nfs/folder /path/to/local/folder
and then you can do the same for the new nfs server
