### ISSUE TITLE
ESTALE 116 Error

### ISSUE THREAD

**Issue by infinitydon** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#142]
Hi,

Currently observing issues with respect to the following scenarios:

- When the NFS server pod restarts due to disruptions in the connectivity between the NFS server pod and the EBS backend volume.
- When the worker-node that is hosting the NFS server pod reboots
- When the worker-node that is hosting the NFS server pod is re-created as a result of EC2 maintenance and the NFS server pod is recreated on a fresh EC2 worker node. 

In all these cases what we notice is that application PODs that are using the mounts goes into stale like the one below

```
user:~$ cd /mounted
-bash: cd: /mounted: Stale file handle
```

Currently manual intervention is always needed by restarting the application pods for them to recover.

Any idea how to resolve this?

**Comment by renierwoo** [comment]
Hello @infinitydon,

Have you managed to resolve that issue? I'm experiencing the same problem as well.

**Comment by renierwoo** [comment]
Hi again, adding the parameter "-device-based-fsids=false" to the deployment/statefulset image's args section solves my problem.
