### ISSUE TITLE
Is Project maintained?

### ISSUE THREAD

**Issue by ptesar-xyndata** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#147]
Dear Team,

I understand that everyone is busy, but before we start using this provisioner, I wanted to ask: is this project still being maintained?

There is a new Ganesha 5.x available, but this project is still using Ganesha 4.x.

Thank you!

**Comment by kvaps** [comment]
Hi @ptesar-xyndata,

This project is currently facing a shortage of maintainers. I am doing my best to review the PRs, but my resources are limited at the moment.

If you feel confident, please feel free to submit a PR. Additionally, if you're interested in joining as a maintainer, I would be glad to sponsor this initiative after a number of contributions.

**Comment by ptesar-xyndata** [comment]
@kvaps I will have a look and maybe I could help. First would be to update and test the newest Ganesha.

**Comment by ader1990** [comment]
Hello, @ptesar-xyndata did you have any success in testing new versions?
