### ISSUE TITLE
No Releases or Updated Changelog

### ISSUE THREAD

**Issue by darkn3rd** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#16]
There are no releases for this project.  It looks some pull requests in the prior read-only project were not pulled across into this version.  It is hard to tell what version this corresponds to as there are no tags or releases.  The helm chart included in this repo is not versioned either (typically there's a branch that communicates the releases to third party helm chart hubs).

The Quay repository referenced in the helm chart shows version 2.3.0, but then nowhere is a tag or release that corresponds to it.

**Comment by bryanasdev000** [comment]
Up.
