### ISSUE TITLE
Sharing NFS folder between two namespaces

### ISSUE THREAD

**Issue by micmoc95** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#18]
Hi,
Using this provisioner works fine when pods share files from storage obtained using the same namespace/PVC as the shared folder name is dynamically created based on namespace/PVC/PV.
How can I manage to share files between two namespaces ?
Regards
Mic

**Comment by kmova** [comment]
This is a restriction from the PVC level at the moment. A pod can use the PVC within its namespace. 

Can you possibly provide some more details on what you want to accomplish using an example?
