### ISSUE TITLE
have the nfs provisioner support hight availability

### ISSUE THREAD

**Issue by sgandon** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#20]
I have been testing the helm chart in order to deploy the nfs provisioner because we would like to use it for production for many dynamic temporary PVs.
All the default values works fine but it creates only one replica of the provisionner (and the server).
For my use case I need to have more relyability and may be more throughput and was hoping to be able to increase the number of replicas.

1/ So I tried to set the `replicaCount=2`. Both replicas started fine. But then we I try to claim a persistent volume it failed.
This is the error from the replica-0
```
controller.go:908] error syncing claim "36caa83a-31f9-4875-bc1d-b4656e06895e": failed to provision volume with StorageClass "nfs":
```
here is the error in the of the pvc
```
  Warning  ProvisioningFailed    38s (x4 over 2m23s)  cluster.local/nfs-nfs-server-provisioner_nfs-nfs-server-provisioner-0_09128ba9-3d58-46eb-bcc2-6318389bc26e  failed to provision volume with StorageClass "nfs": error getting NFS server IP for volume: service SERVICE_NAME=nfs-nfs-server-provisioner is not valid; check that it has for ports map[{111 TCP}:true {111 UDP}:true {662 TCP}:true {662 UDP}:true {875 TCP}:true {875 UDP}:true {2049 TCP}:true {2049 UDP}:true {20048 TCP}:true {20048 UDP}:true {32803 TCP}:true {32803 UDP}:true] exactly one endpoint, this pod's IP POD_IP=10.223.67.159
```
I figured that because it us using a single service in front of a 2 pods then the loadbalancing cannot make this setup work. ( maybe headless service would be more appropriate).

2/ So I have decided to alter the helm chart to disable the `SERVICE_NAME` environment variable by [commenting this](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/83274849f14b3e11567a16fb2d7aa8b5b27dd9c1/deploy/helm/templates/statefulset.yaml#L89-L90). I have seen in the code that the provisioner would use the pod IP so why not give it a try.  
So this works better as the PV managed to be created. but...  
But it seems that only the first replica is managing the PV and the second replica is simply ignored.

Is there a way to make this work ? I am not familiar with the provider mechanism but is it possible that multiple instances may manage different PVs ?

Sorry for this long post, I hope that my questions are clean enough.

**Comment by kmova** [comment]
Will look into this @sgandon and get back.

**Comment by payes** [comment]
Hi @sgandon, NFS HA is not possible using nfs-ganesha-server-and-external-provisioner at this moment.
But have you tried the one provided by rook, I came across this doc which might be helpful as per your requirement.
https://github.com/rook/rook/blob/master/design/ceph/ceph-nfs-ganesha.md

**Comment by sgandon** [comment]
Thanks a lot for the answer, I'll look into that.
