### ISSUE TITLE
Stable helm chart deprecated

### ISSUE THREAD

**Issue by raoul29** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#25]
The documented helm install command:

`helm install stable/nfs-server-provisioner`

gives a deprecated warning as the helm stable repo has been deprecated. Is there a plan to move this to a different helm repo?

**Comment by kvaps** [comment]
This is still on scope
/remove-lifecycle rotten

**Comment by amnk** [comment]
I'm not sure what project priorities are at the moment, but there is a relatively easy way to host charts directly on Github Pages, using [chart-release-action](https://github.com/helm/chart-releaser-action). All it needs is a separate branch, and some configuration for Github and repo structure.
