### ISSUE TITLE
CNCF Artifact Hub repo

### ISSUE THREAD

**Issue by scottrigby** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#27]
Hi, are one of these listed helm charts from this repo?

https://artifacthub.io/packages/search?page=1&ts_query_web=nfs-server-provisioner

If not, this would be good to add.

We have a kubernetes-sigs org there already - let me know if you'd like me to add you.

**Comment by scottrigby** [comment]
Cross-linking:
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/25
- https://github.com/helm/charts/issues/24436

**Comment by kvaps** [comment]
Hi,
My one kvaps/nfs-server-provisioner will follow this repo, we can also consider preparing a new helm repository for this chat.

**Comment by scottrigby** [comment]
@kvaps OK lmk if I can help. Also check out this nice guide that Torsten made based on chart repo relocations I and he worked on https://torstenwalter.de/helm-chart-hosting/

**Comment by euven** [comment]
@kvaps it would be nice to have this chart hosted in a more 'official' spot :) In the meantime, I'll use your repo - thanks!

**Comment by kmova** [comment]
It will be nice to add the GitHub based chart releaser for this repository. Currently, going through this process on a different repo here: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/35

**Comment by rombert** [comment]
This is still relevant IMO.

**Comment by rombert** [comment]
https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/27#issuecomment-831751392
