### ISSUE TITLE
Pods fail when are allocated in a different node to the nfs-provisioner pod is running.

### ISSUE THREAD

**Issue by jorgesece** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#47]
Hi! I tried to use nfs-provisioner with openshift.  
But pods are failing when are allocated in a different node where the nfs-provisioner pod is running. I suppose that it is because CLUSTERIP service is not accessible from pods in different nodes.
Is there another way to expose the provisioner rather than using clusterIP?

```
NAME                                 READY   STATUS              RESTARTS   AGE     IP            NODE                               NOMINATED NODE   READINESS GATES
item-onboard-test                    0/1     ContainerCreating   0          2m18s   <none>        jorge-thks6-worker-eastus1-pc27r   <none>           <none>
item-onboard-test-85c9549869-khfnn   1/1     Running             0          106s    10.129.2.17   jorge-thks6-worker-eastus2-kgcf8   <none>           <none>
item-onboard-test-x7gz2              0/1     ContainerCreating   0          100s    <none>        jorge-thks6-worker-eastus3-xjn78   <none>           <none>
nfs-provisioner-7d898f4fdd-tn6ws     1/1     Running             0          8m37s   10.129.2.14   jorge-thks6-worker-eastus2-kgcf8   <none>           <none>
test                                 1/1     Running             0          2m45s   10.129.2.16   jorge-thks6-worker-eastus2-kgcf8   <none>           <none>
test-no-pvc                          1/1     Running             0          8m36s   10.129.2.13   jorge-thks6-worker-eastus2-kgcf8   <none>           <none>

```

Many thanks,
Jorge

**Comment by consideRatio** [comment]
@jorgesece if you do `kubectl describe pod <a pod that is failing to mount storage>` you get information about what is failing that can be of relevance to consider this.

I have a functional setup where i have multiple nodes that are provisioned storage to pods on the nodes. Note that a k8s cluster requires pod to be able to communicate with other pods etc, and if that isn't functioning, the k8s CNI used to handle networking isn't doing its job or something else is restricting communication or similar.
