### ISSUE TITLE
Migration - pull in changes from external-storage/pull/1320

### ISSUE THREAD

**Issue by kmova** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#5]
Raising this tracker issue to pull in the changes from https://github.com/kubernetes-incubator/external-storage/pull/1320 (cc: @sopak )

**Comment by nikhita** [comment]
Ref: https://github.com/kubernetes-incubator/external-storage/issues/1344

**Comment by darkn3rd** [comment]
What this repo cut from an earlier release that is not supported?
