### ISSUE TITLE
image quay.io/external_storage/nfs-ganesha-server-and-provisioner does not exist

### ISSUE THREAD

**Issue by josecv** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#6]
Hello!

We're playing around with `nfs-ganesha-server-and-external-provisioner`, but our server/provisioner pod is going into ImagePullBackOff:

```
  Warning  Failed     9m48s (x4 over 11m)  kubelet, ip-10-100-89-6.us-west-2.compute.internal  Failed to pull image "quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest": rpc error: code = Unknown desc = Error response from daemon: unauthorized: access to the requested resource is not authorized
  Warning  Failed     9m48s (x4 over 11m)  kubelet, ip-10-100-89-6.us-west-2.compute.internal  Error: ErrImagePull
  Warning  Failed     9m36s (x6 over 11m)  kubelet, ip-10-100-89-6.us-west-2.compute.internal  Error: ImagePullBackOff
  Normal   BackOff    76s (x41 over 11m)   kubelet, ip-10-100-89-6.us-west-2.compute.internal  Back-off pulling image "quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest"
```

pulling the image from the command line doesn't seem to work either, it looks like the image just isn't there on quay.io at all:

```
$ docker pull quay.io/external_storage/nfs-ganesha-server-and-external-provisioner:latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

I don't mind building the image ourselves, but the docs should probably be updated to state that it's not available on quay just yet :)

Cheers!

**Comment by xriser** [comment]
same issue

**Comment by gitlawr** [comment]
Using the previous image `quay.io/kubernetes_incubator/nfs-provisioner:latest`(From the [commit history](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/commit/9c3d3dcb18ab33884d3a662e2409e7b269da5f68)) works for me.

But I'm confused why the change is merged but the image is unavailable.

**Comment by gitlawr** [comment]
Using the previous image `quay.io/kubernetes_incubator/nfs-provisioner:latest` (from [this commit](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/commit/9c3d3dcb18ab33884d3a662e2409e7b269da5f68)) works for me.

I'm confused why the change is merged but the image is unavailable.

**Comment by MyIgel** [comment]
As the previous image crashloops on my k8s I would appreciate newer version

**Comment by xriser** [comment]
https://hub.docker.com/repository/docker/riser/nfs-ganesha-server-and-provisioner
https://hub.docker.com/r/kvaps/nfs-ganesha-server-and-provisioner/tags

**Comment by darkn3rd** [comment]
I am really confused.  The locked original repository has version 5.5.0:
* https://github.com/kubernetes-retired/external-storage/releases/tag/v5.5.0
Then this project has doesn't have any releases but has a changelog that shows version 1.0.8:
* https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/CHANGELOG.md

**Comment by Vinay-Venkatesh** [comment]
same here !!
 
```
Warning  Failed     7s    kubelet            Failed to pull image "quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest": rpc error: code = Unknown desc = Error response from daemon: unauthorized: access to the requested resource is not authorized
Warning  Failed     7s    kubelet            Error: ErrImagePull
Normal   BackOff    6s    kubelet            Back-off pulling image "quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest"
Warning  Failed     6s    kubelet            Error: ImagePullBackOff
```

**Comment by kmova** [comment]
We are in the process of migrating the image building to prow and pushing the images to gcr. 

Currently, the builds are failing with the following error:

```
/go/pkg/mod/github.com/guelfey/go.dbus@v0.0.0-20131113121618-f6a3a2366cc3/transport_unix.go:127:16: undefined: syscall.ParseSocketControlMessage
/go/pkg/mod/github.com/guelfey/go.dbus@v0.0.0-20131113121618-f6a3a2366cc3/transport_unix.go:134:15: undefined: syscall.ParseUnixRights
/go/pkg/mod/github.com/guelfey/go.dbus@v0.0.0-20131113121618-f6a3a2366cc3/transport_unix.go:170:10: undefined: syscall.UnixRights
/go/pkg/mod/github.com/guelfey/go.dbus@v0.0.0-20131113121618-f6a3a2366cc3/transport_unixcred.go:12:12: undefined: syscall.Ucred
/go/pkg/mod/github.com/guelfey/go.dbus@v0.0.0-20131113121618-f6a3a2366cc3/transport_unixcred.go:13:7: undefined: syscall.UnixCredentials
ERROR: (gcloud.builds.submit) build 300b98c2-df7e-481b-a1de-a811da17b66e completed with status "FAILURE"
# github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/mount
/go/pkg/mod/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner@v4.0.0+incompatible/mount/mount.go:21:9: undefined: parseMountTable
Building nfs-provisioner for GOOS=windows GOARCH=amd64 failed, see error(s) above.
make: *** [release-tools/build.make:81: build-nfs-provisioner] Error 1
ERROR
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-nfs-ganesha-server-and-external-provisioner-push-images/1347108662958624768

**Comment by mabushey** [comment]
They don't provide the container, the first thing the docs cover is building and pushing to your own registry. Unfortunately that's the only part where the docs are worth a damn.

**Comment by skandragon** [comment]
This project seems very immature, as it doesn't seem to build and publish images, seems to have no CI set up to do so like other k8s projects, and doesn't give a great sense of confidence in its stability.

The install guide is abysmal.  Of course, "rook" isn't much better, and I can't easily tell if "rook" is a NFS-provisioner or an NFS server...

**Comment by kmova** [comment]
@skandragon @mabushey - the CI is now setup and the images are available here: 

`gcr.io/k8s-staging-sig-storage/nfs-provisioner:canary`

We need some help in updating the docs and adding e2e tests.
