### ISSUE TITLE
Default to use mountOptions.vers=4.2

### ISSUE THREAD

**Issue by consideRatio** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#64]
I asked @yuvipanda whom I learn a lot of NFS matters from about this:

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/027c2eb68e7be2d0d1af6cad2a36cbd64a711b12/deploy/helm/values.yaml#L74-L75

> Yeah, I think the default should be 4.2 since nfs-ganesha supports it, unless they have a strong reason to not do that.

---

Should we transition to suggest 4.2 by default instead?

**Comment by kvaps** [comment]
This change from NFSv4 to NFSv3 was introduced by me in https://github.com/helm/charts/pull/19260

The main reason was in fact that NFSv3 is stateless protocol and works better in such dynamic environment as Kubernetes.
My tests shows that NFSv3 has faster recovery after failure and shows better performance than NFSv4.

Many vendors are using NFSv3 by default, for example [Proxmox](https://www.proxmox.com/en/) and [VMWare](vmware.com) are doing that by providing NFSv4 support just as an additional option.

More details about the differences you can read in this article:
* [A brief look at the difference between NFSv3 and NFSv4](https://thelinuxcluster.com/2012/10/18/a-brief-look-at-the-difference-between-nfsv3-and-nfsv4/)

So I would put the question differently:
What are the benefits we'll get of using 4.2 over 3 by default?

**Comment by consideRatio** [comment]
Ah I wasn't aware of this complexity, and I'm also not very knowledgeable about the tradeoffs in general.

@yuvipanda could you answer what you think regarding benefits of using v4.2 over v3 by default?
