### ISSUE TITLE
Mount PVC as specific user

### ISSUE THREAD

**Issue by cccs-cat001** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#68]
Hi, Is it possible to use this to mount the pvc as a specific user? I see we can mount with a certain gid using that parameter, but then the uid is some random number. There is no parameter option for uid as I've tried, so is there some other way to mount an nfs pvc with a specific uid?

**Comment by kvaps** [comment]
Hi, the in-tree driver is used to mount NFS-volumes in Kubernetes, the implementation is related to this project.

I believe that standard [fsGroup / fsGroupChangePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) should work
