### ISSUE TITLE
Resizing support?

### ISSUE THREAD

**Issue by adarmanto** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#69]
It might still relate to https://github.com/kubernetes-retired/external-storage/issues/1142.

and when I tried to resize the volume it shows this message on the `describe` command:

```
Events:
  Type     Reason             Age                From           Message
  ----     ------             ----               ----           -------
  Warning  ExternalExpanding  42s (x3 over 12h)  volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

Is there any plan to support this feature?

**Comment by kvaps** [comment]
Yeah, @wongma7 answered correct in https://github.com/kubernetes-retired/external-storage/issues/1142#issuecomment-469296488:

> no it does not, note quota i.e. the size of the volume is not enforced, you can request a 1 GiB volume but use more than 1 GiB. this is a limitation for nfs

**Comment by adarmanto** [comment]
Got it so, it also confirmed on this new repo won't add this feature. Just wanted to clarify, thanks!
