### ISSUE TITLE
Problematical use of Filesystem_Id in nfs-ganesha exports

### ISSUE THREAD

**Issue by ffilz** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#7]
In the nfs-ganesha project, we have this issue raised when Export_Id 152 is provisioned:

https://github.com/nfs-ganesha/nfs-ganesha/issues/615

I am wondering why the provisioning is specifying Filesystem_Id? It is not recommended to use this export configuration option for nfs-ganesha and instead allow the underlying filesystem to provide the filesystem ID via a UUID or by the device ID the filesystem is mounted on. There are situations where a stable Filesystem_Id is not available and the option must be specified. One such place is FSAL_PSEUDO exports, in particular the automatically configured FSAL_PSEUDO export for the NFSv4 PseudoFS root. This auto-configured export (Export_Id 0) uses Filesystem_Id 152.152. This is a long standing configuration predating the ability to use UUID or Device ID from the underlying filesystem. The use of Export_Id.Export_Id for the provisioned exports Filesystem_Id is a problem if Export_Id 152 is used. 

If you could either change the Filesystem_Id or eliminate the option, that would be ideal. If not, the best solution would then be to consider Export_Id 152 to also be reserved.

Another option would be for the provisioner to explicitly configure the PseduoFS root and specify a Filesystem_Id that doesn't conflict with the Export_Id.Export_Id ideal. I'm not sure if 0.0 is ok to use, but any X.Y where X and Y are not the same would work.

**Comment by kmova** [comment]
@ffilz - based on the conversation in the https://github.com/nfs-ganesha/nfs-ganesha/issues/615 and to maintain backward compatibility, it sounds appropriate to fix this provisioner to mark 152 as reserved. Thank you for raising this issue!
