### ISSUE TITLE
Increase the timeout for the prow jobs

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#78]
With addition of non-amd64 platforms, now prow job is taking more time to finish building the container images because of the cross-build(qemu simulation mode) and times out for default timeout(2hrs)

Sample job run:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-nfs-ganesha-server-and-external-provisioner-push-images/1459900631392194560

something like this is needed to fix the timeout issue:
https://github.com/kubernetes/test-infra/blob/9299b9708f6c5c15e8a41c2f2b989033f6d239b0/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L13:L15,

**Comment by mkumatag** [comment]
/assign @Rajalakshmi-Girish 
can you ptal

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /assign @Rajalakshmi-Girish can you ptal

Hope just inclusion of `decoration_config:` to the job YAML would work.
I don't see a way to test it before submission. @mkumatag Please correct me if I am wrong.

**Comment by mkumatag** [comment]
> > /assign @Rajalakshmi-Girish can you ptal
> 
> Hope just inclusion of `decoration_config:` to the job YAML would work. I don't see a way to test it before submission. @mkumatag Please correct me if I am wrong.

adding that additional timeout in the decoration_config should fix the issue.
