### ISSUE TITLE
Please add support for pathPattern to match the nfs-subdir provisioner

### ISSUE THREAD

**Issue by Routhinator** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#90]
Hey, would love to see support for the path config to be able to be set for consistent volume naming/grouping on the filesystem as with the nfs-subdir provisioner.

```yaml
pathPattern: "$${.PVC.namespace}/$${.PVC.name}"
```

**Comment by kvaps** [comment]
Currently nfs-server-provisioner creates directories according to PV name. eg:

```
/export/pvc-307c7fe3-ea0a-42b8-a0cd-ae145f155a25
```

I would not want to change this behavior. However we can consider adding symlinks with user friendly names like:
```
/export/by-pvc/<namespace>/<pvc-name> -> ../../pvc-307c7fe3-ea0a-42b8-a0cd-ae145f155a25
```

I think this can be done as part of https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/37 to have deterministic configuration and symlinks each new run.

**Comment by johnnytolengo** [comment]
Hello, will be fine to add a reference (as a prefix) of the PVC name in the NFS Folder.

Currently the PV is created as eg:
` pvc-307c7fe3-ea0a-42b8-a0cd-ae145f155a25`

let's say that my PVC is called: mytest

and what I would like to have in the NFS is something like: 
`mytest-pvc-307c7fe3-ea0a-42b8-a0cd-ae145f155a25` 

In that way I can recongnize which folder belongs to which deployed project.

Could you tell me which source file/function I have to modify?

Regards

**Comment by johnnytolengo** [comment]
Problem solved updated code on provision.go:

PVNamewithprefix := strings.ReplaceAll( string( strings.ToLower(options.PVC.Name) ) , " ", "" ) + "-" + options.PVName
now it's working as I expected :)
