### ISSUE TITLE
nfs-provisioner Apple Silicon M1 ARM support

### ISSUE THREAD

**Issue by pentago** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#91]
Current image doesn't run on newer Macbooks:

```
Failed to pull image "k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0": rpc error: code = N │
│ otFound desc = failed to pull and unpack image "k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0": no match for platform in manifest: not found
```

Any chance ARM variant of this image can be added to the build?

Thanks!

**Comment by pentago** [comment]
ping?

**Comment by fragolinux** [comment]
any news?

**Comment by terion-name** [comment]
same here =((

**Comment by saipradeep01-whs** [comment]
same here. Any fix implemented or work around?

**Comment by fragolinux** [comment]
Moved to openebs nfs provisioner, that has m1 support

**Comment by saipradeep01-whs** [comment]
@fragolinux do you have that link?

**Comment by fragolinux** [comment]
> @fragolinux do you have that link?

It isn't fair to put it here (it wasn't even naming that, honestly, but hey, here we're stuck...), a simple Google search using my terms will bring you to the right place...

**Comment by kvaps** [comment]
> It isn't fair to put it here

Be free to post any links here. We're free community
https://github.com/openebs/dynamic-nfs-provisioner

**Comment by pentago** [comment]
Thank you sir.

**Comment by pentago** [comment]
The thing is, that project that's mentioned in the comment above is trash. Even they call it an alpha-state project and it's lacking so many things.

I think we need M1 build of this particular provisioner as there are no decent alternatives elsewhere.

**Comment by pentago** [comment]
Hopefully this latest comment moves things a bit..
