### ISSUE TITLE
nfs-server afrer update or autoscaling node

### ISSUE THREAD

**Issue by mashkovd** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#93]
Hi, 

In my point.
I have installed [nfs-ganesha-server-and-external-provisioner](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner) by helm.
After deploy app and create PV we have working app and etc.
But when autoscaling or updating node **nfs-server** recreate and we have empty folder export

How i can save data after reinstall nfc server/
Thx

**Comment by yemkay** [comment]
Have you enabled persistence by referring the Readme?
